# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  collect_targets:
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.find_targets.outputs.TARGETS }}

    steps:
      - uses: actions/checkout@v3
      - name: Find targets
        id: find_targets
        run: echo "TARGETS=$(find . -name "*.go" | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      
  run:
    runs-on: ubuntu-latest
    needs: collect_targets

    strategy:
      matrix:
        target: ${{ fromJson(needs.collect_targets.outputs.TARGETS) }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: |
        printf \`\`\` >> $GITHUB_STEP_SUMMARY
        go run ./01/A.go >> $GITHUB_STEP_SUMMARY 2>&1
        printf \`\`\` >> $GITHUB_STEP_SUMMARY

